
server:
  port: 8080
cache: false
spring:
  datasource:
    name: testdb
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: qiaomu
    password:
    schema: classpath:SCHEMA.sql